### ISSUE TITLE
Minimize/maximize bug

### ISSUE THREAD

**Issue by azzoam** [gabr/FixGVimBorder-#3]
Hi!  I've encountered a small bug where I minimize GVim and then upon maximizing again the white border bars reappear.  It can be fixed by resizing the window and then maximizing again, but I wondered if there is a way to keep this from occurring.  Is this bug reproducible for you?  Thanks!

**Comment by gabr** [comment]
Hi, I'm aware of this.

This one is related to automatic background color detection.
When you specify background color manually it should not occur.

That is one of the reasons I recommend to put background color by hand and not rely on automatic detection.

You are free to try write better automatic color detection ;)

**Comment by azzoam** [comment]
Hey Arkadiusz,  I've fixed the automatic color detection issue as well as the maximize bug :).  It's now very stable for me, please review my fork at https://github.com/azzoam/FixGVimBorder.  There are quite a few changes which is why I'm not making a pull request, but if you'd like to bring this functionality into the main repo I will implement your latest commits to make the merge easier.  Changes are highlighted in my latest commit message below.  I suggest reading the README.md as well.

**Major revision** - Added color autodetect and others
--------------------------------------------------------------
Large revision with the following changes:
- added reliable support for color autodection.  This is
now accomplished through a vimscript and the result is passed
to the dll
- restructured the repository as a standard Vim package.  The
entire folder can now be copied to a standard package directory
such as $HOME\vimfiles\bundle
- implementation of the fix for users is greatly simplified,
see README.md
- the dll's now can and should live in the package directory.
No need to copy them to C:\Program Files\Vim\vim80. Therefore
I removed the install.bat files.
- build.bat is slightly changed to address the new package
structure

**Comment by azzoam** [comment]
Also, I haven't brought in your updates to implement LoadGVimFixBorderWithoutAutocentering() yet, so I would recommend turning off the scroll bar and menubar while testing with
``` {vim}
set guioptions -=m
set guioptions -=T
set guioptions -=r
set guioptions -=L
```
I will bring in these changes if we want to merge.


**UPDATE**
Finished merging all commits from your branch and added user-facing code to handle centering issues.
Repo now handles autodetection of whether the patch should try to center and calls the appropriate
functions automatically.

Should now work appropriately no matter what the vimrc scroll bar and menubar settings are.

**Comment by azzoam** [comment]
**UPDATE**
Finished merging all commits from your branch and added user-facing code to handle centering issues.
Repo now handles autodetection of whether the patch should try to center and calls the appropriate
functions automatically

**Comment by azzoam** [comment]
See https://github.com/gabr/FixGVimBorder/pull/4.  Thanks!  Closing issue
